### PR TITLE
feat(afdian): more precise sponsor algorithm

### PR DESCRIPTION
**Pull request by StarHeartHunt**
### Description

There're some edge cases that afdian's open api doesn't cover. When a sponsor choose a lower priced subscription with longer time, the sum usually reached the next subscription price. At this situation, they will be displayed as the next level subscriber while get a longer time of display due to afdian open api doesn't return the amount creator actually get from subscription.

For example, the price of level 1 sub is $5, and for level 2 sub is $10, subscribing level 1 for 2 months can be displayed as a level 2 subscriber and can be displayed for 2 months while directly subscribing level 2 sub costs the same amount but can only be displayed for 1 month.

This pr is going to implement a algorithm directly calculate the monthly income by getting orders data from afdian web api, which requires the `auth_token` in cookies.

### CODE REVIEW

**Comment by antfu** [comment]
Did you created a ticket/issue to afdian about this? I wonder if there is anything they could improve on their side

**Comment by StarHeartHunt** [comment]
> Did you created a ticket/issue to afdian about this? I wonder if there is anything they could improve on their side

it seems the customer service takes time🤔

)J0~DCH4 (X0T0Y_E)YNUOO

**Comment by StarHeartHunt** [comment]
Image_1699177802079

Still no updates from afdian after a month, i think they probably won't add support for this case

**Comment by shigma** [comment]
> Still no updates from afdian after a month, i think they probably won't add support for this case

I suppose he just forgot all about this stuff..... Maybe you should remind him 🤣

**Pull request closed without merging**
